twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic: /nav_vel
        timeout: 0.2
        priority: 10
      keyboard:
        topic: /key_vel
        timeout: 2
        priority: 50
