twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic: /cmd_vel_nav
        timeout: 0.2
        priority: 1
      keyboard:
        topic: /cmd_vel_teleop
        timeout: 0.2
        priority: 2
