<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="dimensions.xacro" />

    <joint name="camera_joint" type="fixed">
        <parent link="chassis" />
        <child link="camera_link" />
        <origin xyz="${chassis_radius - 0.01} 0 ${chassis_length + 0.03}" rpy="0 0.1 0" />
    </joint>

    <link name="camera_link">
        <visual>
            <geometry>
                <box size="0.010 0.03 0.03" />
            </geometry>
            <material name="black" />
        </visual>
        <visual>
            <origin xyz="0 0 -0.015" />
            <geometry>
                <cylinder radius="0.002" length="0.03" />
            </geometry>
            <material name="black" />
        </visual>
    </link>

    <gazebo reference="camera_link">
        <material>Gazebo/Black</material>

        <sensor name="camera" type="camera">
            <camera>
                <horizontal_fov>1.047</horizontal_fov>
                <image>
                    <width>640</width>
                    <height>480</height>
                </image>
                <clip>
                    <near>0.01</near>
                    <far>100</far>
                </clip>
            </camera>
            <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
                <alwaysOn>true</alwaysOn>
                <updateRate>0.0</updateRate>
                <cameraName>camera</cameraName>
                <imageTopicName>image_raw</imageTopicName>
                <cameraInfoTopicName>camera_info</cameraInfoTopicName>
                <frameName>camera_link</frameName>
                <hackBaseline>0.07</hackBaseline>
              </plugin>
            <always_on>1</always_on>
            <update_rate>30</update_rate>
            <visualize>1</visualize>
            <topic>camera</topic>
        </sensor>
    </gazebo>
</robot>