<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="chassis_length" value="0.10" />
    <xacro:property name="chassis_radius" value="0.15" />
    <xacro:property name="chassis_mass" value="1.0" />
    <xacro:property name="wheel_radius" value="0.03" />
    <xacro:property name="wheel_thickness" value="0.02" />
    <xacro:property name="wheel_mass" value="0.05" />
    <xacro:property name="wheel_offset_y" value="${chassis_radius + wheel_thickness/2 + 0.001}" />
    <xacro:property name="wheel_offset_z" value="0.01" />
    <xacro:property name="caster_wheel_radius" value="0.01" />
    <xacro:property name="caster_wheel_mass" value="0.01" />
    <xacro:property name="caster_wheel_offset_x" value="${chassis_radius * 0.9}" />
    <xacro:property name="caster_wheel_offset_z"
        value="${wheel_offset_z - wheel_radius + caster_wheel_radius}" />
</robot>