<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="inertial_macros.xacro" />
    <xacro:include filename="dimensions.xacro" />

    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="grey">
        <color rgba="0.4 0.4 0.4 1" />
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1" />
    </material>

    <material name="black">
        <color rgba="0 0 0 1" />
    </material>

    <material name="red">
        <color rgba="1 0 0 1" />
    </material>

    <!-- BASE LINK -->

    <link name="base_link" />

    <!-- BASE_FOOTPRINT LINK -->

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link" />
        <child link="base_footprint" />
        <origin xyz="0 0 0" rpy="0 0 0" />
    </joint>

    <link name="base_footprint"/>

    <!-- CHASSIS LINK -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link" />
        <child link="chassis" />
        <origin xyz="0 0 ${-wheel_offset_z}" />
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="0 0 ${chassis_length/2}" />
            <geometry>
                <cylinder radius="${chassis_radius}" length="${chassis_length}" />
            </geometry>
            <material name="grey" />
        </visual>
        <collision>
            <origin xyz="0 0 ${chassis_length/2}" />
            <geometry>
                <cylinder radius="${chassis_radius}" length="${chassis_length}" />
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${chassis_mass}" length="${chassis_length}" radius="${chassis_radius}">
            <origin xyz="0 0 ${chassis_length/2}" rpy="0 0 0" />
        </xacro:inertial_cylinder>
    </link>

    <!-- LEFT WHEEL LINK -->

    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="left_wheel" />
        <origin xyz="0 ${wheel_offset_y} 0" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1" />
    </joint>

    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}" />
            </geometry>
            <material name="blue" />
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}" />
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}"
            radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0" />
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>


    <!-- RIGHT WHEEL LINK -->

    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="right_wheel" />
        <origin xyz="0 ${-wheel_offset_y} 0" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1" />
    </joint>

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}" />
            </geometry>
            <material name="blue" />
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}" />
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}"
            radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0" />
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="right_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>


    <!-- CASTER WHEEL LINKS -->

    <joint name="caster_front_joint" type="fixed">
        <parent link="chassis" />
        <child link="caster_wheel_front" />
        <origin xyz="${caster_wheel_offset_x} 0 ${caster_wheel_offset_z+0.001}" />
    </joint>


    <link name="caster_wheel_front">
        <visual>
            <geometry>
                <sphere radius="${caster_wheel_radius}" />
            </geometry>
            <material name="white" />
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius}" />
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0" />
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="caster_wheel_front">
        <material>Gazebo/White</material>
        <mu1 value="0" />
        <mu2 value="0" />
    </gazebo>


    <joint name="caster_back_joint" type="fixed">
        <parent link="chassis" />
        <child link="caster_wheel_back" />
        <origin xyz="${-caster_wheel_offset_x} 0 ${caster_wheel_offset_z+0.001}" />
    </joint>


    <link name="caster_wheel_back">
        <visual>
            <geometry>
                <sphere radius="${caster_wheel_radius}" />
            </geometry>
            <material name="white" />
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius}" />
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0" />
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="caster_wheel_back">
        <material>Gazebo/White</material>
        <mu1 value="0" />
        <mu2 value="0" />
    </gazebo>

</robot>